import {z} from 'zod';
import {validKeys,type Poll,type Vote} from './domain';
import type {Store} from './store';
const dateString=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>{const d=new Date(s+'T12:00:00Z');return !isNaN(+d)&&d.toISOString().slice(0,10)===s;});
const input=z.object({creator:z.object({name:z.string().trim().min(1).max(120),email:z.string().trim().email().max(254).transform(v=>v.toLowerCase()),notify:z.boolean().default(true)}),title:z.string().trim().min(1).max(120),mode:z.enum(['dates','week','month']),start:dateString,end:dateString,from:z.number().int().min(0).max(1410),to:z.number().int().min(30).max(1440),step:z.union([z.literal(30),z.literal(60)]),duration:z.number().int().min(30).max(1440).optional(),timezone:z.string().max(80).refine(t=>{try{new Intl.DateTimeFormat('en',{timeZone:t});return true;}catch{return false;}})}).refine(p=>p.end>=p.start&&(+new Date(p.end)-+new Date(p.start))/86400000<=61&&p.to>p.from&&(p.to-p.from)%p.step===0&&p.from%p.step===0&&(p.duration||p.step)%p.step===0&&(p.duration||p.step)<=p.to-p.from);
const voteInput=z.object({email:z.string().trim().email().max(254).transform(v=>v.toLowerCase()),token:z.string().regex(/^[a-f0-9]{64}$/),name:z.string().trim().min(1).max(80),comment:z.string().trim().max(1000),slots:z.record(z.enum(['yes','maybe','no'])).refine(s=>Object.keys(s).length<=3000)});
const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
const json=(d:unknown,status=200)=>Response.json(d,{status,headers});
// Creator contact details are only returned through the authenticated admin history.
function publicPoll(p:Poll):Poll{const {id,title,mode,start,end,from,to,step,duration,timezone,created,closed,closedAt}=p;return {id,title,mode,start,end,from,to,step,duration,timezone,created,closed,closedAt};}
export async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');}
export function publicVote(v:Vote):Vote{const {id,name,comment,slots}=v;return {id,name,comment,slots};}
export const managementPath=(id:string,token:string)=>`/manage?p=${id}#${token}`;
export type CreatorMailer=(poll:Poll,token:string)=>Promise<void>;
export type VoteNotifier=(poll:Poll,vote:Vote,previous:Vote|undefined,eventKey:string)=>Promise<void>;
export async function handle(request:Request,store:Store,id?:string,notify?:VoteNotifier,creatorMail?:CreatorMailer):Promise<Response>{try{
if(request.method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Origen no permitido.'},403);if(!request.headers.get('content-type')?.includes('application/json'))return json({error:'Formato no permitido.'},415);}
if(id&&!/^p_[a-f0-9]{32}$/.test(id))return json({error:'No encontramos esta consulta.'},404);
if(request.method==='GET'&&id){const poll=await store.getPoll(id);if(!poll)return json({error:'No encontramos esta consulta. Revisa el enlace.'},404);return json({poll:publicPoll(poll),votes:(await store.getVotes(id)).map(publicVote)});}
const raw=await request.text();if(raw.length>200000)return json({error:'La respuesta es demasiado grande.'},413);let body;try{body=JSON.parse(raw);}catch{return json({error:'Revisa los datos enviados.'},400);}
if(request.method==='POST'&&!id){const p=input.parse(body);const managementToken=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');const poll:Poll={...p,manageHash:await hash(managementToken),id:'p_'+crypto.randomUUID().replaceAll('-',''),created:new Date().toISOString()};await store.createPoll(poll);let notificationWarning:string|undefined;if(creatorMail){try{await creatorMail(poll,managementToken);}catch{notificationWarning='Consulta creada. No pudimos enviar el enlace privado por correo; guárdalo desde Gestionar consulta.';}}return json({poll:publicPoll(poll),votes:[],managementToken,notificationWarning},201);}
if(request.method==='PUT'&&id){const p=voteInput.parse(body);const poll=await store.getPoll(id);if(!poll)return json({error:'No encontramos esta consulta.'},404);if(poll.closed)return json({error:'Los registros de esta consulta están cerrados.'},409);const valid=validKeys(poll);if(Object.keys(p.slots).some(k=>!valid.has(k)))return json({error:'Hay horarios fuera del rango de esta consulta.'},400);const editHash=await hash(p.token);const voteId=await hash(id+':'+p.token);const prev=await store.getVote(voteId);if(prev&&(prev.edit_hash!==editHash||prev.poll_id!==id))return json({error:'No puedes editar esta respuesta.'},403);if(prev&&JSON.parse(prev.data).name!==p.name)return json({error:'Para responder con otro nombre, selecciona «Responder como otra persona». La respuesta anterior se conserva.'},409);if(!prev&&(await store.getVotes(id)).length>=200)return json({error:'Esta consulta alcanzó 200 respuestas.'},409);const vote:Vote={id:voteId,name:p.name,email:p.email,comment:p.comment,slots:p.slots};if(await store.saveVote({id:voteId,poll_id:id,edit_hash:editHash,data:JSON.stringify(vote)})===false)return json({error:'No se pudo registrar: la consulta está cerrada o alcanzó su límite de respuestas.'},409);let notificationWarning:string|undefined;
const previous:Vote|undefined=prev?JSON.parse(prev.data):undefined;
const canonical=(v:Vote)=>JSON.stringify({name:v.name,comment:v.comment,slots:Object.entries(v.slots).sort(([a],[b])=>a.localeCompare(b))});
if(notify&&poll.creator?.email&&poll.creator.notify!==false&&(!previous||canonical(previous)!==canonical(vote))){try{await notify(poll,vote,previous,await hash(id+':'+canonical(vote)+':'+(previous?canonical(previous):'new')));}catch{console.error('Creator notification failed for poll',id);notificationWarning='Tu respuesta está guardada, pero no se pudo enviar el aviso por correo al creador.';}}
return json({vote:publicVote(vote),...(notificationWarning?{notificationWarning}:{})});}
return json({error:'Operación no disponible.'},405);
}catch(e){if(e instanceof z.ZodError&&e.issues.some(i=>i.path[0]==='email'))return json({error:'Indica un correo electrónico válido para registrar tu disponibilidad.'},400);if(e instanceof z.ZodError&&e.issues.some(i=>i.path[0]==='creator'))return json({error:'Indica el nombre y un correo válido de quien crea la consulta.'},400);if(e instanceof z.ZodError)return json({error:'Revisa el nombre, las fechas y los horarios. El rango máximo es de 62 días.'},400);console.error('Encuentro storage error',e);return json({error:'No se pudo acceder a las respuestas. Inténtalo nuevamente; tus cambios siguen en pantalla.'},503);}}
